<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrdersAggregator.Core\OrdersAggregator.Core.csproj" />
    <ProjectReference Include="..\OrdersAggregator.Server.Business\OrdersAggregator.Server.Business.csproj" />
  </ItemGroup>
</Project>
