<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <LangVersion>latest</LangVersion>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzers>true</RunAnalyzers>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.txt" Link="BannedSymbols.txt" />
	</ItemGroup>
	<PropertyGroup>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
	</PropertyGroup>
</Project>