namespace OrdersAggregator.Client
{
    using Microsoft.AspNetCore.Components.Web;
    using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

    /// <summary>
    /// Provides the entry point for the Blazor WebAssembly application.
    /// </summary>
    /// <remarks>This class is typically generated by the project template and is not intended to be used
    /// directly. It configures the application's root components and services before starting the WebAssembly
    /// host.</remarks>
    public class Program
    {
        /// <summary>
        /// Configures and runs the Blazor WebAssembly application.
        /// </summary>
        /// <remarks>This is the entry point for the Blazor WebAssembly app. It sets up root components
        /// and configures required services before starting the application.</remarks>
        /// <param name="args">An array of command-line arguments supplied to the application at startup.</param>
        /// <returns>A task that represents the asynchronous operation of running the application.</returns>
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");
            builder.RootComponents.Add<HeadOutlet>("head::after");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            await builder.Build().RunAsync();
        }
    }
}
